MAX_ROWS = 120

FREQ_START = 2400
FREQ_END = 2495

SPECTOOL_PATH = "/home/jproost/spectools/spectool_raw"

DBM_MIN = -110
DBM_MAX = -30

POLL_INTERVAL_MS = 250

HOST = "0.0.0.0"
PORT = 5000

# Analyse tuning
SHORT_WINDOW_SECONDS = 8
LONG_WINDOW_SECONDS = 30

# dBm thresholds
SIGNAL_ACTIVITY_THRESHOLD = -88
STRONG_SIGNAL_THRESHOLD = -75
VERY_STRONG_SIGNAL_THRESHOLD = -65

# Classification tuning
NARROW_MAX_WIDTH_MHZ = 4.0
WIDEBAND_MIN_WIDTH_MHZ = 18.0
PERSISTENCE_HIGH_RATIO = 0.70
PERSISTENCE_MEDIUM_RATIO = 0.40

# Channel scoring weights
WEIGHT_NOISE = 1.0
WEIGHT_PEAK = 1.2
WEIGHT_BUSY = 1.4
WEIGHT_OVERLAP = 1.0
WEIGHT_INTERFERENCE = 1.8